accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

mealplanner/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.recipe_list, name="recipe_list"),
    path('recipes/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipes/add/', views.add_recipe, name='add_recipe'),
    path('recipes/delete/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('recipes/edit/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('recipes/<int:recipe_id>/add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('recipes/ingredient/delete/<int:ingredient_id>/', views.delete_ingredient, name='delete_ingredient'),
    path('recipes/<int:recipe_id>/add_tag/', views.add_tag, name='add_tag'),
    path('recipes/<int:recipe_id>/nutri_data/', views.get_nutri_for_recipe, name='get_nutri_data'),

    path('mealplans/', views.mealplan_list, name='mealplan_list'),
    path('mealplans/add/', views.add_mealplan, name='add_mealplan'),
    path('mealplans/<int:mealplan_id>/', views.mealplan_detail, name='mealplan_detail'),
    path('mealplans/edit/<int:mealplan_id>/', views.mealplan_edit, name='mealplan_edit'),
    path('mealplans/addrecipe/<int:mealplan_id>', views.add_recipe_to_mealplan, name='add_recipe_to_mealplan'),
]

softwareproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("mealplanner.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

mealplanner/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Constants for choices
DIFFICULTY_CHOICES = [
    (1, 'Easy'),
    (2, 'Medium'),
    (3, 'Hard')
]

WEEKDAY_CHOICES = [
    (0, 'Monday'),
    (1, 'Tuesday'),
    (2, 'Wednesday'),
    (3, 'Thursday'),
    (4, 'Friday'),
    (5, 'Saturday'),
    (6, 'Sunday'),
]

MEASUREMENT_UNITS = [
    ('g', 'grams'),
    ('ml', 'milliliters'),
    ('unit', 'units'),
]

NUTRI_COLOURS = [
    (0, 'White'),
    (1, 'Green'),
    (2, 'Amber'),
    (3, 'Red'),
]

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes')
    name = models.CharField(max_length=255)
    difficulty = models.IntegerField(choices=DIFFICULTY_CHOICES)
    time_needed = models.DurationField()  # Stores time in hours, minutes, etc.
    public = models.BooleanField(default=False)
    image_url = models.URLField(max_length=500, blank=True, null=True)
    instructions = models.TextField()

    def __str__(self):
        return self.name

class RecipeNutrition(models.Model):
    recipe = models.OneToOneField(Recipe, on_delete=models.CASCADE, primary_key=True)
    calories = models.FloatField()
    calorie_colour = models.IntegerField(choices=NUTRI_COLOURS)
    fat = models.FloatField()
    fat_colour = models.IntegerField(choices=NUTRI_COLOURS)
    carbs = models.FloatField()
    carbs_colour = models.IntegerField(choices=NUTRI_COLOURS)
    protein = models.FloatField()
    protein_colour = models.IntegerField(choices=NUTRI_COLOURS)

    def __str__(self):
        return self.recipe.name + ' Nutrition'

class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    measurement_unit = models.CharField(max_length=10, choices=MEASUREMENT_UNITS)

    def __str__(self):
        return self.name

class IngredientInRecipe(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='ingredient_recipes')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='recipe_ingredients')
    measurement_amount = models.FloatField()

    def __str__(self):
        return f"{self.measurement_amount} {self.ingredient.measurement_unit} of {self.ingredient.name}"

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class RecipeTag(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='tags')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='recipes')

    class Meta:
        unique_together = ('recipe', 'tag')  # Ensure a recipe can't have the same tag twice

    def __str__(self):
        return f"{self.tag.name}"

class MealPlan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meal_plans')
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class MealPlanItem(models.Model):
    meal_plan = models.ForeignKey(MealPlan, on_delete=models.CASCADE, related_name='meal_plan_items')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='meal_plan_items')
    weekday = models.IntegerField(choices=WEEKDAY_CHOICES)

    def __str__(self):
        return f"{self.meal_plan.name} - {self.recipe.name} on {self.get_weekday_display()}"

mealplanner/views.py
# Import necessary modules and libraries
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.db.models import Q, Sum
from django.views.decorators.csrf import csrf_exempt
from collections import defaultdict

import os
from dotenv import load_dotenv
import json
import markdown
import requests

# Import models, forms, and filters used in the views
from .models import Recipe, RecipeNutrition, IngredientInRecipe, Ingredient, RecipeTag, Tag, MealPlan, MealPlanItem
from .forms import RecipeForm, MealPlanForm, RecipeNutritionForm, RecipeInstructionsForm, IngredientForm, TagForm, MealplanRecipeForm
from .filters import RecipeFilter

# Load environment variables from env file
load_dotenv()

# View to list recipes with optional search and filtering
def recipe_list(request):
    # Show public recipes to non-logged-in users, and both public and user-specific recipes to logged-in users
    if request.user.is_authenticated:
        recipes = Recipe.objects.filter(user=request.user) | Recipe.objects.filter(public=True)
    else:
        recipes = Recipe.objects.filter(public=True)
    
    query = request.GET.get('q')

    # Create filters form and apply search query if provided
    recipe_filter = RecipeFilter(request.GET, queryset=recipes)

    # If a search has been made
    if query:
        # Filter recipes based on search term in the name field
        recipes = recipes.filter(
            Q(name__icontains=query) | Q(instructions__icontains=query)
        ).distinct()
    else:
        # If no search, use the values from filter
        recipes = recipe_filter.qs

    # Render the recipe list template with the filtered recipes and context
    context = {
        'active_path': 'recipes',
        'new_recipe_form': RecipeForm(),
        'recipe_filter': recipe_filter,
        'recipes': recipes,
        'query': query,
    }

    return render(request, 'mealplanner/recipe_list.html', context)

# View to search for recipes by name
def recipe_search(request, search_query):
    # Filter recipes based on the search query and user authentication
    if request.user.is_authenticated:
        recipes = Recipe.objects.filter(user=request.user) | Recipe.objects.filter(public=True)
        recipes = recipes.filter(name=search_query)
    else:
        recipes = Recipe.objects.filter(public=True).filter(name=search_query)

    # Render the recipe list template with the search results
    context = {
        'active_path': 'recipes',
        'recipes': recipes,
    }

    return render(request, 'mealplanner/recipe_list.html', context)

# View to display the details of a specific recipe
def recipe_detail(request, recipe_id):
    # Fetch the recipe and ensure the user has permission to view it
    recipe = get_object_or_404(Recipe, id=recipe_id)
    
    # Ensure the user can only view their own recipes or public ones
    if not recipe.public and recipe.user != request.user:
        return HttpResponseForbidden("You are not allowed to view this recipe.")
    
    # Retrieve associated ingredients and nutrition data
    ingredients = IngredientInRecipe.objects.filter(recipe=recipe)

    try:
        nutrition = RecipeNutrition.objects.get(recipe=recipe)
    except:
        nutrition = None

    # Convert recipe instructions from Markdown to HTML
    md = markdown.Markdown()
    recipe.instructions = md.convert(recipe.instructions)

    # Render the recipe detail template with the recipe data
    context = {
        'active_path': 'recipes',
        'recipe': recipe,
        'ingredients': ingredients,
        'nutrition': nutrition
    }

    return render(request, 'mealplanner/recipe_detail.html', context)

# Utility function to fetch nutrition data from an external API
def get_nutrition_data(query, app_id, app_key):
    # Define the API endpoint and headers
    url = 'https://trackapi.nutritionix.com/v2/natural/nutrients'
    headers = {
        'Content-Type': 'application/json',
        'x-app-id': app_id,
        'x-app-key': app_key
    }
    body = {
        "query": query
    }

    # Make a POST request to the API and handle errors
    try:
        response = requests.post(url, headers=headers, data=json.dumps(body))
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx and 5xx)
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None

# View to add a new recipe
@login_required
def add_recipe(request):
    # Handle form submission for creating a new recipe
    if request.method == 'POST':
        new_recipe_form = RecipeForm(request.POST)
        if new_recipe_form.is_valid():
            recipe = new_recipe_form.save(commit=False)
            recipe.user = request.user  # Associate the recipe with the logged-in user
            recipe.save()
            return redirect('edit_recipe', recipe_id=recipe.id)
    
    # Render the add recipe template with the form
    form = RecipeForm()
    return render(request, 'mealplanner/add_recipe.html', {'new_recipe_form': form})

# View to add a new meal plan
@login_required
def add_mealplan(request):
    # Handle form submission for creating a new meal plan
    if request.method == 'POST':
        new_mealplan_form = MealPlanForm(request.POST)
        if new_mealplan_form.is_valid():
            mealplan = new_mealplan_form.save(commit=False)
            mealplan.user = request.user  # Associate the recipe with the logged-in user
            mealplan.save()
            return redirect('mealplan_edit', mealplan_id=mealplan.id)
    
    # Render the add meal plan template with the form
    form = MealPlanForm()
    return render(request, 'mealplanner/add_mealplan.html', {'new_mealplan_form': form})

# View to add a recipe to a meal plan
@login_required
def add_recipe_to_mealplan(request, mealplan_id):
    # Handle form submission for adding a recipe to a meal plan
    if request.method == 'POST':
        add_recipe_form = MealplanRecipeForm(request.POST)
        if add_recipe_form.is_valid():
            mealplan_item = add_recipe_form.save(commit=False)
            mealplan_item.weekday = 0
            mealplan_item.meal_plan = MealPlan.objects.get(id=mealplan_id)
            mealplan_item.save()
    return redirect('mealplan_edit', mealplan_id=mealplan_id)

# View to edit an existing recipe
@login_required
def edit_recipe(request, recipe_id):
    # Fetch the recipe and ensure the user has permission to edit it
    recipe = get_object_or_404(Recipe, id=recipe_id)
    ingredients = Ingredient.objects.all().order_by('name')

    # Ensure the user can only edit their own recipes
    if recipe.user != request.user:
        return HttpResponseForbidden("You are not allowed to edit this recipe.")

    # Handle form submissions for updating recipe details, instructions, or nutrition
    if request.method == 'POST':
        if request.POST['form_id'] == 'recipe_details':
            recipedetailsform = RecipeForm(request.POST, instance=recipe)
            if recipedetailsform.is_valid():
                recipedetailsform.save()
            
            return redirect('edit_recipe', recipe_id=recipe.id)

        if request.POST['form_id'] == 'recipe_instructions':
            recipeinstructionsform = RecipeInstructionsForm(request.POST, instance=recipe)
            if recipeinstructionsform.is_valid():
                recipeinstructionsform.save()
            
            return redirect('edit_recipe', recipe_id=recipe.id)
      

        if request.POST['form_id'] == 'recipe_nutrition':
            receipenutritionform = RecipeNutritionForm(request.POST)
            if receipenutritionform.is_valid():
                nutrition = receipenutritionform.save(commit=False)
                nutrition.recipe = recipe
                nutrition.save()
            
            return redirect('edit_recipe', recipe_id=recipe.id)
            

    else:
        recipedetailsform = RecipeForm(instance=recipe)
        recipeinstructionsform = RecipeInstructionsForm(instance=recipe)
        
        try:
            recipenutrition = RecipeNutrition.objects.get(recipe=recipe)
            receipenutritionform = RecipeNutritionForm(instance=recipenutrition)
        except:
            receipenutritionform = RecipeNutritionForm()

    # Render the edit recipe template with the forms and recipe data
    context = {
        'active_path': 'recipes',
        'recipedetailsform': recipedetailsform,
        'recipeinstructionsform': recipeinstructionsform,
        'receipenutritionform': receipenutritionform,
        'ingredients': ingredients,
        'recipe': recipe
    }

    return render(request, 'mealplanner/edit_recipe.html', context)

# Utility view to fetch nutrition data for a recipe
@login_required
def get_nutri_for_recipe(request, recipe_id):
    # Fetch the recipe and its ingredients
    recipe = get_object_or_404(Recipe, id=recipe_id)
    ingredients_in_recipe = IngredientInRecipe.objects.filter(recipe=recipe)

    APP_ID = os.getenv('APP_ID')
    APP_KEY = os.getenv('APP_KEY')

    # String to store the natural language list of ingredients
    ingredients_natural = ""
    
    # Iterate through ingredients and add to string
    for ingredient in ingredients_in_recipe:
        ingredients_natural += str(ingredient.measurement_amount) + ' ' + str(ingredient.ingredient.measurement_unit) + ' of ' + str(ingredient.ingredient.name) + '; '

    # Call the external API to retrieve nutrition data
    nutrition_data = get_nutrition_data(ingredients_natural, APP_ID, APP_KEY)

    # Vars to store the nutrition parameters
    calories = 0
    fat = 0
    carbs = 0
    protein = 0

    if nutrition_data:
        # Iterate through response and extract nutri params
        for food in nutrition_data['foods']:

mealplanner/templates/mealplanner/add_mealplan.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create recipe
{% endblock %}

{% block maincontent %}
<div class="row">
    <div class="col-12 col-lg-6">

        <h1>Add New Recipe</h1>

        <form method="POST">
            {% csrf_token %}

            {{new_recipe_form|crispy}}

            <button type="submit" class="btn btn-primary">Create recipe</button>
        </form>

        <a href="{% url 'recipe_list' %}">Back to Recipe List</a>

    </div>
</div>
{% endblock %}

mealplanner/templates/mealplanner/add_recipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create recipe
{% endblock %}

{% block maincontent %}
<div class="row">
    <div class="col-12 col-lg-6">

        <h1>Add New Recipe</h1>

        <form method="POST">
            {% csrf_token %}

            {{new_recipe_form|crispy}}

            <button type="submit" class="btn btn-primary">Create recipe</button>
        </form>

        <a href="{% url 'recipe_list' %}">Back to Recipe List</a>

    </div>
</div>
{% endblock %}

mealplanner/templates/mealplanner/ingredient_item.html
<tr id="ingredient-{{ ingredient.id }}">
    <th>{{ ingredient.measurement_amount }} {{ ingredient.ingredient.get_measurement_unit_display }}
    </th>
    <td>{{ ingredient.ingredient.name }}</td>
    <td>
        <button hx-delete="{% url 'delete_ingredient' ingredient.id %}" hx-target="#ingredient-{{ ingredient.id }}"
            hx-swap="outerHTML" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            class="btn btn-outline-danger btn-sm btn-sm">
            Remove
        </button>
    </td>
</tr>

mealplanner/templates/mealplanner/recipe_detail.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}
View recipe
{% endblock %}

{% block maincontent %}
<div class="row">

    <div class="col-md-4">
        {% if recipe.image_url %}
        <img src="{{ recipe.image_url }}" class="img-fluid w-100 rounded" alt="{{ recipe.name }}">
        {% endif %}

        <div class="mb-3">
            <h1 class="mt-3 h2">{{ recipe.name }}</h1>

            <div>
                <p class="mb-2">
                    <i class="bi bi-info-circle"></i> <strong>Difficulty:</strong> {{recipe.get_difficulty_display}}
                </p>
                <p class="mb-2">
                    <i class="bi bi-stopwatch"></i> <strong>Time needed:</strong>
                    {{recipe.time_needed|humanise_duration}}
                </p>
                <p class="mb-2">
                    <i class="bi bi-people"></i> <strong>Public:</strong> {{recipe.public|yesno:"Yes,No"}}
                </p>
            </div>
        </div>

        <div class="mb-3">
            <h2 class="h3">Nutrition</h2>
            {% if nutrition %}

            <div class="d-flex flex-row flex-wrap gap-2 text-center">
                <div class="py-2 px-3 rounded d-flex flex-column gap-2 border m-0
                            {% if nutrition.calorie_colour == 1 %} bg-success-subtle
                                        {% elif nutrition.calorie_colour == 2 %} bg-warning-subtle
                                        {% elif nutrition.calorie_colour == 3 %} bg-danger-subtle {% endif %}">
                    <p class="p-0 m-0">Calories</p>
                    <p class="h5 p-0 m-0">{{ nutrition.calories }} Kcal</p>
                    <p class="p-0 m-0">
                        {% if nutrition.calorie_colour == 1 %} Low
                        {% elif nutrition.calorie_colour == 2 %} Medium
                        {% elif nutrition.calorie_colour == 3 %} High{% endif %}
                    </p>
                </div>
                <div class="py-2 px-3 rounded d-flex flex-column gap-2 border m-0
                            {% if nutrition.fat_colour == 1 %} bg-success-subtle
                                        {% elif nutrition.fat_colour == 2 %} bg-warning-subtle
                                        {% elif nutrition.fat_colour == 3 %} bg-danger-subtle {% endif %}">
                    <p class="p-0 m-0">Fat</p>
                    <p class="h5 p-0 m-0">{{ nutrition.fat }}g</p>
                    <p class="p-0 m-0">
                        {% if nutrition.fat_colour == 1 %} Low
                        {% elif nutrition.fat_colour == 2 %} Medium
                        {% elif nutrition.fat_colour == 3 %} High{% endif %}
                    </p>
                </div>
                <div class="py-2 px-3 rounded d-flex flex-column gap-2 border m-0
                            {% if nutrition.carbs_colour == 1 %} bg-success-subtle
                                        {% elif nutrition.carbs_colour == 2 %} bg-warning-subtle
                                        {% elif nutrition.carbs_colour == 3 %} bg-danger-subtle {% endif %}">
                    <p class="p-0 m-0">Carbs</p>
                    <p class="h5 p-0 m-0">{{ nutrition.carbs }}g</p>
                    <p class="p-0 m-0">
                        {% if nutrition.carbs_colour == 1 %} Low
                        {% elif nutrition.carbs_colour == 2 %} Medium
                        {% elif nutrition.carbs_colour == 3 %} High{% endif %}
                    </p>
                </div>
                <div class="py-2 px-3 rounded d-flex flex-column gap-2 border m-0
                            {% if nutrition.protein_colour == 1 %} bg-success-subtle
                                        {% elif nutrition.protein_colour == 2 %} bg-warning-subtle
                                        {% elif nutrition.protein_colour == 3 %} bg-danger-subtle {% endif %}">
                    <p class="p-0 m-0">Protein</p>
                    <p class="h5 p-0 m-0">{{ nutrition.protein }}g</p>
                    <p class="p-0 m-0">
                        {% if nutrition.protein_colour == 1 %} Low
                        {% elif nutrition.protein_colour == 2 %} Medium
                        {% elif nutrition.protein_colour == 3 %} High{% endif %}
                    </p>
                </div>
            </div>

            {% else %}

            <p>No nutrition data available</p>

            {% endif %}
        </div>

        {% if request.user == recipe.user %}
        <a class="btn btn-secondary" href="{% url 'edit_recipe' recipe.id %}">Edit recipe</a>
        {% endif %}


    </div>

    <div class="col-md-8">

        <div class="d-flex align-items-center flex-md-row flex-column justify-content-between">
            <h2 class="h3">Ingredients</h2>

            <div class="input-group" style="max-width: 10rem;">
                <span class="input-group-text" id="basic-addon1">Servings</span>
                <input type="number" class="form-control" id="servings" value="1" min="1" oninput="scaleIngredients()">
            </div>
        </div>


        <table class="table">
            <tbody>
                {% for ingredient in ingredients %}
                <tr>
                    <th>{{ ingredient.ingredient.name }}</th>
                    <!-- Store the original measurement amount as a data attribute -->
                    <td data-original-amount="{{ ingredient.measurement_amount }}">
                        <span class="scaled-amount">{{ ingredient.measurement_amount }}</span>
                        {{ ingredient.ingredient.get_measurement_unit_display }}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">No ingredients found for this recipe</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <script>
            function scaleIngredients() {
                // Get the number of servings from the input
                const servings = document.getElementById("servings").value;

                // Select all elements with the class "scaled-amount"
                const ingredients = document.querySelectorAll("td[data-original-amount]");

                ingredients.forEach((ingredient) => {
                    // Get the original amount from the data attribute
                    const originalAmount = parseFloat(ingredient.getAttribute("data-original-amount"));

                    // Calculate the new amount based on the servings
                    const scaledAmount = (originalAmount * servings).toFixed(2); // Limit to 2 decimal places

                    // Update the displayed amount
                    ingredient.querySelector(".scaled-amount").textContent = scaledAmount;
                });
            }
        </script>


        <h2 class="h3">Method</h2>
        <p>{{ recipe.instructions|safe }}</p>

    </div>

</div>
{% endblock %}

mealplanner/templates/mealplanner/recipe_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}

{% block title %}
View recipes
{% endblock %}

{% block navbuttons %}

{% if user.is_authenticated %}
<!-- New recipe modal -->
<button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#new-recipe-modal">
    <i class="bi bi-plus"></i> New recipe
</button>
{% endif %}

{% endblock %}

{% block maincontent %}
<div class="row my-3">

    <div class="col-sm-3">
        <div class="row mb-3">

            <h2 class="h4">Filter</h2>

            <form method="GET">
                {{ recipe_filter.form|crispy }}
                <button class="btn btn-primary" type="submit">Filter</button>
                <a href="{% url 'recipe_list' %}" class="btn btn-secondary">Clear filters</a>
            </form>

        </div>
    </div>

    <div class="col-sm-9">

        <div class="row mb-3">

            <div class="col">
                <form class="d-flex" role="search" method="GET" action="{% url 'recipe_list' %}">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-info" type="submit">Search</button>
                </form>
            </div>

        </div>

        <div class="row gy-3">

            <div>
                {% if query %}
                <p class="d-inline me-3 h5">You searched for <strong>{{ query }}</strong></p>
                {% endif %}

                {% if query %}
                <a href="{% url 'recipe_list' %}">Clear search</a>
                {% endif %}
            </div>

            {% if user.is_authenticated %}
            <h2>My recipes</h2>
            {% endif %}


            {% for recipe in recipes %}
            {% if recipe.user == request.user %}
            <div class="col-6 col-md-4 col-xxl-3">
                <a href="{% url 'recipe_detail' recipe.id %}"
                    class="link-dark link-underline-opacity-0 link-underline-opacity-25-hover link-offset-2">
                    <div class="card h-100">
                        {% if recipe.image_url %}
                        <img src="{{ recipe.image_url }}" class="card-img-top" alt="{{ recipe.name }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>

                            <div class="d-flex justify-content-between">
                                <p class="card-text mb-1">
                                    {{ recipe.get_difficulty_display }}
                                </p>
                                <p class="card-text mb-1">
                                    {{ recipe.time_needed|humanise_duration }}
                                </p>
                            </div>

                            <p class="card-text">
                                <i class="bi bi-tag"></i>
                                {% if recipe.tags.all %}
                                {{ recipe.tags.all|join:", " }}
                                {% else %}
                                No tags
                                {% endif %}
                            </p>

                        </div>
                    </div>
                </a>
            </div>
            {% endif %}

            {% empty %}

            <p>No recipes available.</p>

            {% endfor %}


            <h2>Public recipes</h2>
            {% for recipe in recipes %}
            {% if recipe.user != request.user %}
            <div class="col-6 col-md-4 col-xxl-3">
                <a href="{% url 'recipe_detail' recipe.id %}"
                    class="link-dark link-underline-opacity-0 link-underline-opacity-25-hover link-offset-2">
                    <div class="card h-100">
                        {% if recipe.image_url %}
                        <img src="{{ recipe.image_url }}" class="card-img-top" alt="{{ recipe.name }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>

                            <div class="d-flex justify-content-between">
                                <p class="card-text mb-1">
                                    {{ recipe.get_difficulty_display }}
                                </p>
                                <p class="card-text mb-1">
                                    {{ recipe.time_needed|humanise_duration }}
                                </p>
                            </div>

                            <p class="card-text">
                                <i class="bi bi-tag"></i>
                                {% if recipe.tags.all %}
                                {{ recipe.tags.all|join:", " }}
                                {% else %}
                                No tags
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}

            {% empty %}

            <p>No recipes available.</p>

            {% endfor %}

        </div>

    </div>

</div>
{% endblock %}


{% block modal %}
<!-- New recipe modal -->
<div class="modal fade" id="new-recipe-modal" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal-title-2"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modal-title-2">New recipe</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form action="{% url 'add_recipe' %}" method="POST">
                    {% csrf_token %}

                    {{new_recipe_form|crispy}}

                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-primary">Create recipe</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

mealplanner/templates/mealplanner/tag_item.html
<li>{{ tag.name }}</li>